title: JOAN R. BELLIDO
email: jrbellido@gmail.com
description: >- 
  Personal notes on software engineering and other stuff
baseurl: "" 
url: "https://jrbellido.github.io" 
twitter_username: jrbellido 
github_username:  jrbellido

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - resources/

