name = "wagon theme"
description = "A custom theme"
license = "MIT"
homepage = "https://jrbellido.github.io/"
min_version = "0.4.0"
demo = "https://jrbellido.github.io/"

[extra]

[author]
name = "Joan R. Bellido"
homepage = "https://jrbellido.github.io/"

