name: cobalt-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - uses: saidgeek/cobalt-deploy-gh-pages
      with:
        githubToken: 9cf3e6b1bb76fc7f070b6c907888e02b13abef5f
