name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out to $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      
    - name: Install cobalt
      run: |
        wget https://github.com/cobalt-org/cobalt.rs/releases/download/v0.15.11/cobalt-v0.15.11-x86_64-unknown-linux-gnu.tar.gz -O /tmp/cobalt.tar.gz
        mkdir /tmp/cobalt && cd /tmp/cobalt && tar xvfz /tmp/cobalt.tar.gz
        cd $GITHUB_WORKSPACE
        /tmp/cobalt/cobalt build
        echo Done.
